// src/pages/Privacy.js
import React from 'react';
import { Link } from 'react-router-dom';

const Privacy = () => {
  const updated = 'July 19, 2025';

  const sections = [
    { id: 'introduction',  title: '1. Introduction' },
    { id: 'information',   title: '2. Information We Collect' },
    { id: 'use',           title: '3. How We Use Your Information' },
    { id: 'protection',    title: '4. Data Protection' },
    { id: 'third-parties', title: '5. Third-Party Services' },
    { id: 'contact',       title: '6. Contact Us' },
  ];

  return (
    <main className="min-h-screen bg-[var(--bg)] text-[var(--ink)]">
      <div className="max-w-4xl mx-auto px-6 md:px-8 lg:px-10 py-12">
        <header className="mb-6">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">
            Last updated: <time dateTime="2025-07-19">{updated}</time>
          </p>
        </header>

        {/* Table of contents */}
        <nav
          aria-label="Table of contents"
          className="mb-8 rounded-lg border border-slate-200 dark:border-slate-800 bg-white/70 dark:bg-slate-900/70 backdrop-blur px-4 py-3"
        >
          <ul className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
            {sections.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-slate-700 dark:text-slate-300 hover:text-blue-700 dark:hover:text-blue-300"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        <article className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm">
          <div className="p-6 md:p-8">
            {/* 1. Introduction */}
            <section id="introduction" className="mb-8 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                1. Introduction
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                Your privacy is important to us. This Privacy Policy outlines how JobTracker
                collects, uses, and protects your personal information.
              </p>
            </section>

            {/* 2. Information We Collect */}
            <section id="information" className="mb-8 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                2. Information We Collect
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-3">
                We collect information you provide directly and data generated by your use of the platform:
              </p>
              <ul className="list-disc pl-6 text-slate-700 dark:text-slate-300 leading-relaxed space-y-1">
                <li>Name, email address, account credentials.</li>
                <li>Resume/CV files, portfolio details, job application data.</li>
                <li>Usage data (e.g., pages viewed, actions taken) to improve performance and features.</li>
              </ul>
            </section>

            {/* 3. How We Use Your Information */}
            <section id="use" className="mb-8 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                3. How We Use Your Information
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                We use your information to provide and improve the JobTracker service, personalize
                your experience, and send relevant updates or notifications related to your account
                and activity.
              </p>
            </section>

            {/* 4. Data Protection */}
            <section id="protection" className="mb-8 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                4. Data Protection
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                We implement industry-standard security measures to protect your data from
                unauthorized access, alteration, or disclosure. However, no method of transmission
                over the Internet or electronic storage is 100% secure.
              </p>
            </section>

            {/* 5. Third-Party Services */}
            <section id="third-parties" className="mb-8 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                5. Third-Party Services
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                We may use third-party tools (e.g., analytics, file storage, or payment providers).
                These services may collect information in accordance with their own privacy policies.
              </p>
            </section>

            {/* 6. Contact Us */}
            <section id="contact" className="mb-2 scroll-mt-24">
              <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2">
                6. Contact Us
              </h2>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                For any privacy-related inquiries, reach out to{' '}
                <a
                  href="mailto:privacy@jobtracker.com"
                  className="text-blue-700 dark:text-blue-300 underline underline-offset-2 hover:opacity-90"
                >
                  privacy@jobtracker.com
                </a>{' '}
  or you can contact us directly{' '}
  <Link
    to="/contact"
    className="text-blue-700 dark:text-blue-300 underline underline-offset-2 hover:opacity-90"
  >
    here
  </Link>.
              </p>
            </section>
          </div>

          {/* Footer strip of the article */}
          <div className="px-6 md:px-8 py-4 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-600 dark:text-slate-400">
            © {new Date().getFullYear()} JobTracker • Read our{' '}
            <Link to="/terms" className="text-blue-700 dark:text-blue-300 hover:underline">
              Terms &amp; Conditions
            </Link>
            .
          </div>
        </article>
      </div>
    </main>
  );
};

export default Privacy;
